const express = require("express");
const cors = require("cors");
const app = express();
app.use(cors());
app.use(express.json());

let ConversationTitle = {
  items: [
    {
      id: "6a8223f4-6acc-83ea-a932-a6dafd68acf7",
      title: "Greeting Exchange",
      create_time: "2026-08-16T20:56:28.357758Z",
      update_time: "2026-08-16T20:56:31.664379Z",
      pinned_time: null,
      mapping: null,
      current_node: null,
      conversation_template_id: null,
      gizmo_id: null,
      is_archived: false,
      is_starred: null,
      is_temporary_chat: false,
      is_do_not_remember: false,
      memory_scope: "global_enabled",
      context_scopes: null,
      context_scopes_v2: {
        context_scopes: [
          {
            is_siloed: false,
            scope_namespace: "global",
            sub_scope: null,
            key: null,
            key_timestamp: null,
            key_scoped_access_claim: null,
          },
        ],
      },
      workspace_id: null,
      async_status: null,
      safe_urls: [],
      blocked_urls: [],
      conversation_origin: null,
      is_automation_conversation: false,
      snippet: null,
      sugar_item_id: null,
      sugar_item_visible: false,
    },
    {
      id: "6a81d3d4-d364-83ea-87e7-98bedb6d4a3f",
      title: "3-ball juggling tips",
      create_time: "2026-08-16T15:15:37.058108Z",
      update_time: "2026-08-16T15:22:32.372405Z",
      pinned_time: null,
      mapping: null,
      current_node: null,
      conversation_template_id: null,
      gizmo_id: null,
      is_archived: false,
      is_starred: null,
      is_temporary_chat: false,
      is_do_not_remember: false,
      memory_scope: "global_enabled",
      context_scopes: null,
      context_scopes_v2: {
        context_scopes: [
          {
            is_siloed: false,
            scope_namespace: "global",
            sub_scope: null,
            key: null,
            key_timestamp: null,
            key_scoped_access_claim: null,
          },
        ],
      },
      workspace_id: null,
      async_status: null,
      safe_urls: [],
      blocked_urls: [],
      conversation_origin: null,
      is_automation_conversation: false,
      snippet: null,
      sugar_item_id: null,
      sugar_item_visible: false,
    },
    {
      id: "6a7f0ec3-d72c-83ea-9540-e8a3a0e12f6e",
      title: "Phone Drop Input Issue",
      create_time: "2026-08-14T12:49:37.539157Z",
      update_time: "2026-08-14T12:50:03.029396Z",
      pinned_time: null,
      mapping: null,
      current_node: null,
      conversation_template_id: null,
      gizmo_id: null,
      is_archived: false,
      is_starred: null,
      is_temporary_chat: false,
      is_do_not_remember: false,
      memory_scope: "global_enabled",
      context_scopes: null,
      context_scopes_v2: {
        context_scopes: [
          {
            is_siloed: false,
            scope_namespace: "global",
            sub_scope: null,
            key: null,
            key_timestamp: null,
            key_scoped_access_claim: null,
          },
        ],
      },
      workspace_id: null,
      async_status: null,
      safe_urls: [],
      blocked_urls: [],
      conversation_origin: null,
      is_automation_conversation: false,
      snippet: null,
      sugar_item_id: null,
      sugar_item_visible: false,
    },
    {
      id: "6a7af021-fe8c-83ea-b7ca-40641870db65",
      title: "Organize Code Migration",
      create_time: "2026-08-11T09:50:31.875309Z",
      update_time: "2026-08-12T03:16:15.226767Z",
      pinned_time: null,
      mapping: null,
      current_node: null,
      conversation_template_id: null,
      gizmo_id: null,
      is_archived: false,
      is_starred: null,
      is_temporary_chat: false,
      is_do_not_remember: false,
      memory_scope: "global_enabled",
      context_scopes: null,
      context_scopes_v2: {
        context_scopes: [
          {
            is_siloed: false,
            scope_namespace: "global",
            sub_scope: null,
            key: null,
            key_timestamp: null,
            key_scoped_access_claim: null,
          },
        ],
      },
      workspace_id: null,
      async_status: null,
      safe_urls: [],
      blocked_urls: [],
      conversation_origin: null,
      is_automation_conversation: false,
      snippet: null,
      sugar_item_id: null,
      sugar_item_visible: false,
    },
    {
      id: "6a79e126-a870-83ea-838d-bd168f60cc65",
      title: "Channel Art Request",
      create_time: "2026-08-10T14:33:34.854267Z",
      update_time: "2026-08-10T14:39:35.732111Z",
      pinned_time: null,
      mapping: null,
      current_node: null,
      conversation_template_id: null,
      gizmo_id: null,
      is_archived: false,
      is_starred: null,
      is_temporary_chat: false,
      is_do_not_remember: false,
      memory_scope: "global_enabled",
      context_scopes: null,
      context_scopes_v2: {
        context_scopes: [
          {
            is_siloed: false,
            scope_namespace: "global",
            sub_scope: null,
            key: null,
            key_timestamp: null,
            key_scoped_access_claim: null,
          },
        ],
      },
      workspace_id: null,
      async_status: null,
      safe_urls: [],
      blocked_urls: [],
      conversation_origin: null,
      is_automation_conversation: false,
      snippet: null,
      sugar_item_id: null,
      sugar_item_visible: false,
    },
    {
      id: "6a79d9cb-4ae4-83ea-bf95-856cd2e0b138",
      title: "Greeting a User",
      create_time: "2026-08-10T14:01:52.772096Z",
      update_time: "2026-08-10T14:01:54.787397Z",
      pinned_time: null,
      mapping: null,
      current_node: null,
      conversation_template_id: null,
      gizmo_id: null,
      is_archived: false,
      is_starred: null,
      is_temporary_chat: false,
      is_do_not_remember: false,
      memory_scope: "global_enabled",
      context_scopes: null,
      context_scopes_v2: {
        context_scopes: [
          {
            is_siloed: false,
            scope_namespace: "global",
            sub_scope: null,
            key: null,
            key_timestamp: null,
            key_scoped_access_claim: null,
          },
        ],
      },
      workspace_id: null,
      async_status: null,
      safe_urls: [],
      blocked_urls: [],
      conversation_origin: null,
      is_automation_conversation: false,
      snippet: null,
      sugar_item_id: null,
      sugar_item_visible: false,
    },
    {
      id: "6a78d41f-1d48-83ea-b40d-cf959155334a",
      title: "Search Icon to Input",
      create_time: "2026-08-09T19:26:19.145077Z",
      update_time: "2026-08-09T19:58:07.165775Z",
      pinned_time: null,
      mapping: null,
      current_node: null,
      conversation_template_id: null,
      gizmo_id: null,
      is_archived: false,
      is_starred: null,
      is_temporary_chat: false,
      is_do_not_remember: false,
      memory_scope: "global_enabled",
      context_scopes: null,
      context_scopes_v2: {
        context_scopes: [
          {
            is_siloed: false,
            scope_namespace: "global",
            sub_scope: null,
            key: null,
            key_timestamp: null,
            key_scoped_access_claim: null,
          },
        ],
      },
      workspace_id: null,
      async_status: null,
      safe_urls: [],
      blocked_urls: [],
      conversation_origin: null,
      is_automation_conversation: false,
      snippet: null,
      sugar_item_id: null,
      sugar_item_visible: false,
    },
    {
      id: "6a78c445-4eb8-83ea-b682-e416f8b9a8ab",
      title: "Greeting Exchange",
      create_time: "2026-08-09T18:17:42.417282Z",
      update_time: "2026-08-09T18:21:42.232318Z",
      pinned_time: null,
      mapping: null,
      current_node: null,
      conversation_template_id: null,
      gizmo_id: null,
      is_archived: false,
      is_starred: null,
      is_temporary_chat: false,
      is_do_not_remember: false,
      memory_scope: "global_enabled",
      context_scopes: null,
      context_scopes_v2: {
        context_scopes: [
          {
            is_siloed: false,
            scope_namespace: "global",
            sub_scope: null,
            key: null,
            key_timestamp: null,
            key_scoped_access_claim: null,
          },
        ],
      },
      workspace_id: null,
      async_status: null,
      safe_urls: [],
      blocked_urls: [],
      conversation_origin: null,
      is_automation_conversation: false,
      snippet: null,
      sugar_item_id: null,
      sugar_item_visible: false,
    },
    {
      id: "6a72ffea-94cc-83ea-8a2d-9982b1d98d7b",
      title: "User History Summary",
      create_time: "2026-08-05T09:18:35.505402Z",
      update_time: "2026-08-05T09:18:42.844254Z",
      pinned_time: null,
      mapping: null,
      current_node: null,
      conversation_template_id: null,
      gizmo_id: null,
      is_archived: false,
      is_starred: null,
      is_temporary_chat: false,
      is_do_not_remember: false,
      memory_scope: "global_enabled",
      context_scopes: null,
      context_scopes_v2: {
        context_scopes: [
          {
            is_siloed: false,
            scope_namespace: "global",
            sub_scope: null,
            key: null,
            key_timestamp: null,
            key_scoped_access_claim: null,
          },
        ],
      },
      workspace_id: null,
      async_status: null,
      safe_urls: [],
      blocked_urls: [],
      conversation_origin: null,
      is_automation_conversation: false,
      snippet: null,
      sugar_item_id: null,
      sugar_item_visible: false,
    },
    {
      id: "6a706f24-372c-83ea-ae9e-106975cbb7b8",
      title: "Premium editorial portrait",
      create_time: "2026-08-03T10:36:25.778986Z",
      update_time: "2026-08-03T10:37:11.627586Z",
      pinned_time: null,
      mapping: null,
      current_node: null,
      conversation_template_id: null,
      gizmo_id: null,
      is_archived: false,
      is_starred: null,
      is_temporary_chat: false,
      is_do_not_remember: false,
      memory_scope: "global_enabled",
      context_scopes: null,
      context_scopes_v2: {
        context_scopes: [
          {
            is_siloed: false,
            scope_namespace: "global",
            sub_scope: null,
            key: null,
            key_timestamp: null,
            key_scoped_access_claim: null,
          },
        ],
      },
      workspace_id: null,
      async_status: null,
      safe_urls: [],
      blocked_urls: [],
      conversation_origin: null,
      is_automation_conversation: false,
      snippet: null,
      sugar_item_id: null,
      sugar_item_visible: false,
    },
    {
      id: "6a706c3b-67b4-83ea-a6d1-a4b14b51d38e",
      title: "AI Image Prompt Creation",
      create_time: "2026-08-03T10:24:19.288124Z",
      update_time: "2026-08-03T10:35:30.835292Z",
      pinned_time: null,
      mapping: null,
      current_node: null,
      conversation_template_id: null,
      gizmo_id: null,
      is_archived: false,
      is_starred: null,
      is_temporary_chat: false,
      is_do_not_remember: false,
      memory_scope: "global_enabled",
      context_scopes: null,
      context_scopes_v2: {
        context_scopes: [
          {
            is_siloed: false,
            scope_namespace: "global",
            sub_scope: null,
            key: null,
            key_timestamp: null,
            key_scoped_access_claim: null,
          },
        ],
      },
      workspace_id: null,
      async_status: null,
      safe_urls: [],
      blocked_urls: [],
      conversation_origin: null,
      is_automation_conversation: false,
      snippet: null,
      sugar_item_id: null,
      sugar_item_visible: false,
    },
    {
      id: "6a703e7e-27d4-83ea-ae5a-81540ccb69a8",
      title: "When to Take Antagit-SS",
      create_time: "2026-08-03T07:09:10.932949Z",
      update_time: "2026-08-03T07:11:09.645326Z",
      pinned_time: null,
      mapping: null,
      current_node: null,
      conversation_template_id: null,
      gizmo_id: null,
      is_archived: false,
      is_starred: null,
      is_temporary_chat: false,
      is_do_not_remember: false,
      memory_scope: "global_enabled",
      context_scopes: null,
      context_scopes_v2: {
        context_scopes: [
          {
            is_siloed: false,
            scope_namespace: "global",
            sub_scope: null,
            key: null,
            key_timestamp: null,
            key_scoped_access_claim: null,
          },
        ],
      },
      workspace_id: null,
      async_status: null,
      safe_urls: [],
      blocked_urls: [],
      conversation_origin: null,
      is_automation_conversation: false,
      snippet: null,
      sugar_item_id: null,
      sugar_item_visible: false,
    },
    {
      id: "6a6ed197-e910-83ea-aec7-482c83af3018",
      title: "Happy birthday repetition",
      create_time: "2026-08-02T05:11:52.665374Z",
      update_time: "2026-08-02T05:23:25.379796Z",
      pinned_time: null,
      mapping: null,
      current_node: null,
      conversation_template_id: null,
      gizmo_id: null,
      is_archived: false,
      is_starred: null,
      is_temporary_chat: false,
      is_do_not_remember: false,
      memory_scope: "global_enabled",
      context_scopes: null,
      context_scopes_v2: {
        context_scopes: [
          {
            is_siloed: false,
            scope_namespace: "global",
            sub_scope: null,
            key: null,
            key_timestamp: null,
            key_scoped_access_claim: null,
          },
        ],
      },
      workspace_id: null,
      async_status: null,
      safe_urls: [],
      blocked_urls: [],
      conversation_origin: null,
      is_automation_conversation: false,
      snippet: null,
      sugar_item_id: null,
      sugar_item_visible: false,
    },
    {
      id: "6a6ca68f-5c8c-83ea-bf56-1d4ed2544973",
      title: "Delete New Gmail Account",
      create_time: "2026-07-31T13:43:49.297050Z",
      update_time: "2026-07-31T13:53:39.751919Z",
      pinned_time: null,
      mapping: null,
      current_node: null,
      conversation_template_id: null,
      gizmo_id: null,
      is_archived: false,
      is_starred: null,
      is_temporary_chat: false,
      is_do_not_remember: false,
      memory_scope: "global_enabled",
      context_scopes: null,
      context_scopes_v2: {
        context_scopes: [
          {
            is_siloed: false,
            scope_namespace: "global",
            sub_scope: null,
            key: null,
            key_timestamp: null,
            key_scoped_access_claim: null,
          },
        ],
      },
      workspace_id: null,
      async_status: null,
      safe_urls: [],
      blocked_urls: [],
      conversation_origin: null,
      is_automation_conversation: false,
      snippet: null,
      sugar_item_id: null,
      sugar_item_visible: false,
    },
  ],
  total: 29,
  limit: 28,
  offset: 0,
};
let chatHistory = [
  {
    title: "Greeting Exchange",
    create_time: 1786913788.357758,
    update_time: 1786913793.31237,
    moderation_results: [],
    plugin_ids: null,
    conversation_id: "6a8223f4-6acc-83ea-a932-a6dafd68acf7",
    conversation_template_id: null,
    gizmo_id: null,
    gizmo_type: null,
    is_archived: false,
    is_starred: null,
    safe_urls: [
      "https://www.progressive.com",
      "https://www.apple.com/",
      "https://github.com/openclaw/openclaw",
      "https://www.openai.com",
      "https://www.statefarm.com",
      "https://docs.google.com/document/d/",
    ],
    blocked_urls: [],
    default_model_slug: "auto",
    atlas_mode_enabled: null,
    conversation_origin: null,
    is_read_only: null,
    voice: null,
    async_status: null,
    disabled_tool_ids: [],
    is_temporary_chat: false,
    is_do_not_remember: false,
    memory_scope: "global_enabled",
    context_scopes: null,
    sugar_item_id: null,
    sugar_item_visible: false,
    pinned_time: null,
    is_study_mode: false,
    owner: null,
    mapping: {
      "client-created-root": {
        id: "client-created-root",
        message: null,
        parent: null,
        children: ["80bf5df7-5ed8-48cb-ac27-2eaa20413766"],
      },
      "80bf5df7-5ed8-48cb-ac27-2eaa20413766": {
        id: "80bf5df7-5ed8-48cb-ac27-2eaa20413766",
        message: {
          id: "80bf5df7-5ed8-48cb-ac27-2eaa20413766",
          author: {
            role: "user",
            name: null,
            metadata: {},
          },
          create_time: 1786913785.764,
          update_time: 1786913793.310605,
          content: {
            content_type: "text",
            parts: ["hi"],
          },
          status: "finished_successfully",
          end_turn: null,
          weight: 1.0,
          metadata: {
            serialization_metadata: {
              custom_symbol_offsets: [],
            },
            request_id: "809b5a5a-ebd5-4c35-af0a-c7f0979c7cce",
            message_source: null,
            turn_exchange_id: "cdb5edae-5b59-4952-8494-17f09fa9644d",
            working_turn_id: "cdb5edae-5b59-4952-8494-17f09fa9644d",
            resolved_model_slug: "gpt-5-6",
            can_save: false,
          },
          recipient: "all",
          channel: null,
        },
        parent: "client-created-root",
        children: ["b0824378-1b8c-48da-90b9-370b9f4f555f"],
      },
      "b0824378-1b8c-48da-90b9-370b9f4f555f": {
        id: "b0824378-1b8c-48da-90b9-370b9f4f555f",
        message: {
          id: "b0824378-1b8c-48da-90b9-370b9f4f555f",
          author: {
            role: "assistant",
            name: null,
            metadata: {},
          },
          create_time: 1786913787.622675,
          update_time: 1786913792.919544,
          content: {
            content_type: "text",
            parts: [
              "Hey! 👋😄  \nGood to see you again! What are we working on tonight?",
            ],
          },
          status: "finished_successfully",
          end_turn: true,
          weight: 1.0,
          metadata: {
            finish_details: {
              type: "stop",
              stop_tokens: [200002],
            },
            is_complete: true,
            citations: [],
            content_references: [],
            resolved_model_slug: "gpt-5-6",
            search_result_groups: [],
            cot_version: "v5",
            request_id: "809b5a5a-ebd5-4c35-af0a-c7f0979c7cce",
            message_type: "next",
            turn_exchange_id: "cdb5edae-5b59-4952-8494-17f09fa9644d",
            working_turn_id: "cdb5edae-5b59-4952-8494-17f09fa9644d",
            model_slug: "gpt-5-6",
            default_model_slug: "auto",
            can_save: true,
            parent_id: "9cdb4373-a2ac-42ba-9bfd-caac55ce25ba",
            model_switcher_deny: [],
          },
          recipient: "all",
          channel: "final",
        },
        parent: "80bf5df7-5ed8-48cb-ac27-2eaa20413766",
        children: [],
      },
    },
    current_node: "b0824378-1b8c-48da-90b9-370b9f4f555f",
    context_truncation_continuation: null,
  },
  {
    title: "User History Summary",
    create_time: 1785921515.505402,
    update_time: 1785921523.859253,
    moderation_results: [],
    plugin_ids: null,
    conversation_id: "6a72ffea-94cc-83ea-8a2d-9982b1d98d7b",
    conversation_template_id: null,
    gizmo_id: null,
    gizmo_type: null,
    is_archived: false,
    is_starred: null,
    safe_urls: [
      "https://www.apple.com/",
      "https://www.openai.com",
      "https://www.progressive.com",
      "https://docs.google.com/document/d/",
      "https://github.com/openclaw/openclaw",
      "https://www.statefarm.com",
    ],
    blocked_urls: [],
    default_model_slug: "auto",
    atlas_mode_enabled: null,
    conversation_origin: null,
    is_read_only: null,
    voice: null,
    async_status: null,
    disabled_tool_ids: [],
    is_temporary_chat: false,
    is_do_not_remember: false,
    memory_scope: "global_enabled",
    context_scopes: null,
    sugar_item_id: null,
    sugar_item_visible: false,
    pinned_time: null,
    is_study_mode: false,
    owner: null,
    mapping: {
      "client-created-root": {
        id: "client-created-root",
        message: null,
        parent: null,
        children: ["b03751ed-2be6-472a-9d67-5cc5d2c3449f"],
      },
      "b03751ed-2be6-472a-9d67-5cc5d2c3449f": {
        id: "b03751ed-2be6-472a-9d67-5cc5d2c3449f",
        message: {
          id: "b03751ed-2be6-472a-9d67-5cc5d2c3449f",
          author: {
            role: "user",
            name: null,
            metadata: {},
          },
          create_time: 1785921514.594,
          update_time: 1785921523.856906,
          content: {
            content_type: "text",
            parts: ["tell me about me based on my previous history"],
          },
          status: "finished_successfully",
          end_turn: null,
          weight: 1.0,
          metadata: {
            serialization_metadata: {
              custom_symbol_offsets: [],
            },
            request_id: "0e919ac7-3ab7-48a6-924b-2679a2becb78",
            message_source: null,
            turn_exchange_id: "a391a492-353d-49b1-b686-d9cc1ae91cdd",
            working_turn_id: "a391a492-353d-49b1-b686-d9cc1ae91cdd",
            resolved_model_slug: "gpt-5-5",
            can_save: false,
          },
          recipient: "all",
          channel: null,
        },
        parent: "client-created-root",
        children: ["def0886e-a62c-43d7-898b-5dd1d258dd58"],
      },
      "def0886e-a62c-43d7-898b-5dd1d258dd58": {
        id: "def0886e-a62c-43d7-898b-5dd1d258dd58",
        message: {
          id: "def0886e-a62c-43d7-898b-5dd1d258dd58",
          author: {
            role: "assistant",
            name: null,
            metadata: {},
          },
          create_time: 1785921515.413675,
          update_time: 1785921523.554982,
          content: {
            content_type: "text",
            parts: [
              "Based on our previous conversations, here's a summary of what I've learned about you.\n\n### Who you are\n- Your name is **Alazar Eshete**.\n- You're from **Ethiopia**, and **Amharic** is your native language.\n- You also work on improving your **English**, especially your speaking and pronunciation, and you prefer an **American accent**.\n\n### Your education\n- You're a university student who has studied topics including:\n  - C++ programming\n  - Mathematics\n  - Physics\n  - Public Ethics\n  - Global Trends\n  - Emerging Technologies\n  - Teamwork\n- You prefer learning by **understanding concepts deeply** rather than memorizing.\n- You often ask for:\n  - Step-by-step explanations\n  - Simple language\n  - Real-life examples\n  - Short summaries before diving deeper\n\n### Your interests\nYou have a strong interest in:\n- Artificial Intelligence\n- Technology\n- Programming\n- Personal growth\n- Productivity\n- Content creation\n- Graphic design and AI-generated art\n\nYou've spent a lot of time creating cinematic portraits and social media graphics with AI.\n\n### Your YouTube goals\nYou created the **AlinaTech** YouTube channel focused on:\n- AI news\n- AI tools\n- Technology tutorials\n\nYou've asked for help with:\n- Scripts\n- Thumbnails\n- Logos\n- Banners\n- Content ideas\n\n### Your style\nFrom the images and prompts you've created, you seem to like:\n- Minimalist designs\n- Black backgrounds\n- Red accent lighting\n- Cinematic, luxury, editorial photography\n- Clean typography\n\n### Your technology\nYou use:\n- An **HP laptop** running Windows 11.\n- Gmail and GitHub, and you've had questions about changing your Google email address and how it affects other services.\n\n### Your health questions\nYou've asked about:\n- Medication timing.\n- Battery health (for your laptop).\n- Face skincare.\n- Sleep.\n- Exercise-related pain.\n\nThese were informational questions rather than ongoing discussions.\n\n### How you like ChatGPT to help\nYou usually prefer:\n- Direct answers\n- Detailed explanations when learning\n- Practical advice\n- Examples\n- Help with studying and technology\n\n### Overall impression\nYou come across as someone who is:\n- Curious about new technology.\n- Motivated to improve your skills.\n- Interested in building something meaningful online.\n- Willing to spend time refining your work until it looks professional.\n- Someone who asks follow-up questions until a topic fully makes sense.\n\nOne thing I've noticed is that when you're working on a goal—whether it's studying for an exam, designing an image, or solving a technical problem—you tend to iterate several times instead of settling for the first result. That persistence has been a consistent pattern across our conversations.",
            ],
          },
          status: "finished_successfully",
          end_turn: true,
          weight: 1.0,
          metadata: {
            finish_details: {
              type: "stop",
              stop_tokens: [200002],
            },
            is_complete: true,
            citations: [],
            content_references: [],
            resolved_model_slug: "gpt-5-5",
            search_result_groups: [],
            cot_version: "v5",
            request_id: "0e919ac7-3ab7-48a6-924b-2679a2becb78",
            message_type: "next",
            turn_exchange_id: "a391a492-353d-49b1-b686-d9cc1ae91cdd",
            working_turn_id: "a391a492-353d-49b1-b686-d9cc1ae91cdd",
            model_slug: "gpt-5-5",
            default_model_slug: "auto",
            can_save: true,
            parent_id: "f32a7098-577e-46d2-ac1e-fb7264daa319",
            model_switcher_deny: [],
          },
          recipient: "all",
          channel: "final",
        },
        parent: "b03751ed-2be6-472a-9d67-5cc5d2c3449f",
        children: [],
      },
    },
    current_node: "def0886e-a62c-43d7-898b-5dd1d258dd58",
    context_truncation_continuation: null,
  },
  {
    title: "Phone Drop Input Issue",
    create_time: 1786711777.539157,
    update_time: 1786711804.00688,
    moderation_results: [],
    plugin_ids: null,
    conversation_id: "6a7f0ec3-d72c-83ea-9540-e8a3a0e12f6e",
    conversation_template_id: null,
    gizmo_id: null,
    gizmo_type: null,
    is_archived: false,
    is_starred: null,
    safe_urls: [
      "https://www.openai.com",
      "https://www.progressive.com",
      "https://github.com/openclaw/openclaw",
      "https://www.statefarm.com",
      "https://www.apple.com/",
      "https://docs.google.com/document/d/",
    ],
    blocked_urls: [],
    default_model_slug: "auto",
    atlas_mode_enabled: null,
    conversation_origin: null,
    is_read_only: null,
    voice: null,
    async_status: null,
    disabled_tool_ids: [],
    is_temporary_chat: false,
    is_do_not_remember: false,
    memory_scope: "global_enabled",
    context_scopes: null,
    sugar_item_id: null,
    sugar_item_visible: false,
    pinned_time: null,
    is_study_mode: false,
    owner: null,
    mapping: {
      "client-created-root": {
        id: "client-created-root",
        message: null,
        parent: null,
        children: ["d0f469a7-b990-4694-9115-628f49ed94fe"],
      },
      "d0f469a7-b990-4694-9115-628f49ed94fe": {
        id: "d0f469a7-b990-4694-9115-628f49ed94fe",
        message: {
          id: "d0f469a7-b990-4694-9115-628f49ed94fe",
          author: {
            role: "user",
            name: null,
            metadata: {},
          },
          create_time: 1786711776.437,
          update_time: 1786711782.462567,
          content: {
            content_type: "text",
            parts: [
              "if someone drop his phone and the input part there is something not working ",
            ],
          },
          status: "finished_successfully",
          end_turn: null,
          weight: 1.0,
          metadata: {
            serialization_metadata: {
              custom_symbol_offsets: [],
            },
            request_id: "18a83169-d10a-4e5b-b8cf-f5fb9f398c54",
            message_source: null,
            turn_exchange_id: "2ce8cc6d-c2db-4f66-beb7-6095fdc08d50",
            working_turn_id: "2ce8cc6d-c2db-4f66-beb7-6095fdc08d50",
            resolved_model_slug: "gpt-5-6",
            can_save: false,
          },
          recipient: "all",
          channel: null,
        },
        parent: "client-created-root",
        children: ["64dfdae4-abcb-4a8f-9e26-4358036659f1"],
      },
      "64dfdae4-abcb-4a8f-9e26-4358036659f1": {
        id: "64dfdae4-abcb-4a8f-9e26-4358036659f1",
        message: {
          id: "64dfdae4-abcb-4a8f-9e26-4358036659f1",
          author: {
            role: "assistant",
            name: null,
            metadata: {},
          },
          create_time: 1786711777.404363,
          update_time: 1786711782.109465,
          content: {
            content_type: "text",
            parts: [
              "Yes. If someone **drops their phone** and afterward something in the **input/touch area** stops working, it could be physical damage.\n\nIf by “input part” you mean the **touchscreen**, common possibilities are:\n\n- 📱 **Digitizer damage** — the screen displays normally, but some areas don't respond to touch.\n- 🔌 **Loose display/digitizer connector** — the impact can partially disconnect the screen internally.\n- 💥 **Screen damage** — sometimes there is no visible crack, but the touch layer underneath is damaged.\n- ⚡ **Motherboard/connector damage** — less common, but possible after a hard drop.\n\n### Quick test\nOpen the phone's keyboard and tap **every key**, especially in the area that isn't responding. You can also drag an icon around the screen and see whether it stops when it reaches a particular area.\n\nIf **one specific section of the screen doesn't respond while the rest works**, that's a strong sign of digitizer/display damage rather than a software problem.\n\nIf you tell me **the phone model** and **exactly which input isn't working** (touchscreen, keyboard, charging port, SIM slot, microphone, etc.), I can tell you what is most likely damaged and whether it's worth repairing.",
            ],
          },
          status: "finished_successfully",
          end_turn: true,
          weight: 1.0,
          metadata: {
            finish_details: {
              type: "stop",
              stop_tokens: [200002],
            },
            is_complete: true,
            citations: [],
            content_references: [],
            resolved_model_slug: "gpt-5-6",
            search_result_groups: [],
            cot_version: "v5",
            request_id: "18a83169-d10a-4e5b-b8cf-f5fb9f398c54",
            message_type: "next",
            turn_exchange_id: "2ce8cc6d-c2db-4f66-beb7-6095fdc08d50",
            working_turn_id: "2ce8cc6d-c2db-4f66-beb7-6095fdc08d50",
            model_slug: "gpt-5-6",
            default_model_slug: "auto",
            can_save: true,
            parent_id: "f5d62b10-f89d-49df-ba27-46604f974142",
            model_switcher_deny: [],
          },
          recipient: "all",
          channel: "final",
        },
        parent: "d0f469a7-b990-4694-9115-628f49ed94fe",
        children: ["8790edc1-97f0-4187-9c0f-fcfe5f6cc416"],
      },
      "8790edc1-97f0-4187-9c0f-fcfe5f6cc416": {
        id: "8790edc1-97f0-4187-9c0f-fcfe5f6cc416",
        message: {
          id: "8790edc1-97f0-4187-9c0f-fcfe5f6cc416",
          author: {
            role: "user",
            name: null,
            metadata: {},
          },
          create_time: 1786711800.424,
          update_time: 1786711804.004923,
          content: {
            content_type: "text",
            parts: ["speaker i can hear but not to talk"],
          },
          status: "finished_successfully",
          end_turn: null,
          weight: 1.0,
          metadata: {
            serialization_metadata: {
              custom_symbol_offsets: [],
            },
            request_id: "7ca53413-ad8f-45bd-bfef-f11f4229cbe2",
            message_source: null,
            turn_exchange_id: "cca053a5-d0e7-49bb-9fad-5218d05e1024",
            working_turn_id: "cca053a5-d0e7-49bb-9fad-5218d05e1024",
            resolved_model_slug: "gpt-5-6",
            can_save: false,
          },
          recipient: "all",
          channel: null,
        },
        parent: "64dfdae4-abcb-4a8f-9e26-4358036659f1",
        children: ["af55239e-0773-45a8-a108-5deea5d14158"],
      },
      "af55239e-0773-45a8-a108-5deea5d14158": {
        id: "af55239e-0773-45a8-a108-5deea5d14158",
        message: {
          id: "af55239e-0773-45a8-a108-5deea5d14158",
          author: {
            role: "assistant",
            name: null,
            metadata: {},
          },
          create_time: 1786711800.90443,
          update_time: 1786711803.731076,
          content: {
            content_type: "text",
            parts: [
              "Ah, got you 👍 You mean:\n\n- 🔊 **You can hear the other person** → speaker/earpiece works.\n- 🎤 **They can't hear you when you talk** → the **microphone** is likely not working.\n\nSince the phone was **dropped**, the most likely causes are:\n\n1. **Microphone damaged** by the impact.\n2. **Microphone opening blocked** by dirt or a case.\n3. **Internal microphone connection became loose.**\n4. Less commonly, a software/app issue.\n\n### Quick test\nOpen the phone's **Voice Recorder** and record yourself speaking.\n\n- If the recording is **silent or extremely faint** → the microphone hardware is probably damaged.\n- If the recording sounds normal → the microphone works, and the problem may be with the calling app/settings.\n\nAlso try a **normal phone call** and a call on **WhatsApp/Telegram**. If nobody can hear you on any of them, that points more strongly to the microphone itself.\n\nIf you tell me the **phone model** (Samsung, iPhone, Tecno, Infinix, etc.), I can tell you where its microphone is and what to check.",
            ],
          },
          status: "finished_successfully",
          end_turn: true,
          weight: 1.0,
          metadata: {
            finish_details: {
              type: "stop",
              stop_tokens: [200002],
            },
            is_complete: true,
            citations: [],
            content_references: [],
            resolved_model_slug: "gpt-5-6",
            search_result_groups: [],
            cot_version: "v5",
            request_id: "7ca53413-ad8f-45bd-bfef-f11f4229cbe2",
            message_type: "next",
            turn_exchange_id: "cca053a5-d0e7-49bb-9fad-5218d05e1024",
            working_turn_id: "cca053a5-d0e7-49bb-9fad-5218d05e1024",
            model_slug: "gpt-5-6",
            default_model_slug: "auto",
            can_save: true,
            parent_id: "8790edc1-97f0-4187-9c0f-fcfe5f6cc416",
            model_switcher_deny: [],
          },
          recipient: "all",
          channel: "final",
        },
        parent: "8790edc1-97f0-4187-9c0f-fcfe5f6cc416",
        children: [],
      },
    },
    current_node: "af55239e-0773-45a8-a108-5deea5d14158",
    context_truncation_continuation: null,
  },
];

app.get("/", (req, res) => {
  {
    console.log("IT WORKS");
    res.send("IT WORKS");
  }
});

app.get("/conversations", (req, res) => {
  res.json(ConversationTitle.items);
});

app.get("/conversations/:id", (req, res) => {
  const convo_id = req.params.id;
  const convo = chatHistory?.find((chat) => chat.conversation_id === convo_id);
  res.json(convo);
});

app.listen(1080, () => {
  console.log("Server running on http://localhost:1080");
});
